version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "build"
      include: "scope"
    rebase-strategy: "auto"
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "build"
      include: "scope"
    rebase-strategy: "auto"
    schedule:
      interval: "weekly"
