name: on-commit

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  labeler:
    name: apply labels
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/labeler@v6.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml
          sync-labels: true

  lint-commit-messages:
    name: lint commit message
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Commitizen check
        run: |
          uvx --from commitizen cz check --rev-range HEAD^!
  lint-pr-title:
    # default: lints titles using https://github.com/commitizen/conventional-commit-types
    name: lint pr title
    runs-on: [ubuntu-latest]
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
